# Generated by Django 5.1.5 on 2025-02-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_alter_comment_options_alter_healthreport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicalstandard',
            name='run_50m_pass',
            field=models.FloatField(default=9.0, verbose_name='50米跑及格标准(秒)'),
        ),
        migrations.AddField(
            model_name='physicalstandard',
            name='run_800m_pass',
            field=models.IntegerField(default=240, verbose_name='800米跑及格标准(秒)'),
        ),
        migrations.AddField(
            model_name='physicalstandard',
            name='sit_and_reach_pass',
            field=models.IntegerField(default=10, verbose_name='坐位体前屈及格标准(cm)'),
        ),
        migrations.AddField(
            model_name='physicalstandard',
            name='standing_jump_pass',
            field=models.IntegerField(default=180, verbose_name='立定跳远及格标准(cm)'),
        ),
        migrations.AddField(
            model_name='physicalstandard',
            name='vital_capacity_pass',
            field=models.IntegerField(default=2000, verbose_name='肺活量及格标准(ml)'),
        ),
        migrations.AddField(
            model_name='testplan',
            name='plan_type',
            field=models.CharField(choices=[('regular', '常规测试'), ('makeup', '补考测试')], default='regular', max_length=10, verbose_name='计划类型'),
        ),
        migrations.CreateModel(
            name='MakeupNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('original_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.testresult', verbose_name='原始成绩')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.student', verbose_name='学生')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.testplan', verbose_name='补考计划')),
            ],
            options={
                'verbose_name': '补考通知',
                'verbose_name_plural': '补考通知管理',
                'db_table': 'makeup_notification',
            },
        ),
    ]
