# Generated by Django 5.1.5 on 2025-02-04 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '评论', 'verbose_name_plural': '评论管理'},
        ),
        migrations.AlterModelOptions(
            name='healthreport',
            options={'verbose_name': '健康报告', 'verbose_name_plural': '健康报告管理'},
        ),
        migrations.AlterModelOptions(
            name='physicalstandard',
            options={'verbose_name': '体测标准', 'verbose_name_plural': '体测标准管理'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': '学生', 'verbose_name_plural': '学生管理'},
        ),
        migrations.AlterModelOptions(
            name='testplan',
            options={'verbose_name': '测试计划', 'verbose_name_plural': '测试计划管理'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': '测试成绩', 'verbose_name_plural': '测试成绩管理'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户管理'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='是否批准'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.testresult', verbose_name='测试成绩'),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='health_suggestions',
            field=models.TextField(verbose_name='健康建议'),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='overall_assessment',
            field=models.TextField(verbose_name='总体评估'),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='test_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness.testresult', verbose_name='测试成绩'),
        ),
        migrations.AlterField(
            model_name='physicalstandard',
            name='bmi_max',
            field=models.FloatField(verbose_name='BMI最大值'),
        ),
        migrations.AlterField(
            model_name='physicalstandard',
            name='bmi_min',
            field=models.FloatField(verbose_name='BMI最小值'),
        ),
        migrations.AlterField(
            model_name='physicalstandard',
            name='gender',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='physicalstandard',
            name='run_50m_excellent',
            field=models.FloatField(verbose_name='50米跑优秀标准(秒)'),
        ),
        migrations.AlterField(
            model_name='physicalstandard',
            name='run_800m_excellent',
            field=models.IntegerField(verbose_name='800米跑优秀标准(秒)'),
        ),
        migrations.AlterField(
            model_name='physicalstandard',
            name='sit_and_reach_excellent',
            field=models.IntegerField(verbose_name='坐位体前屈优秀标准(cm)'),
        ),
        migrations.AlterField(
            model_name='physicalstandard',
            name='standing_jump_excellent',
            field=models.IntegerField(verbose_name='立定跳远优秀标准(cm)'),
        ),
        migrations.AlterField(
            model_name='physicalstandard',
            name='vital_capacity_excellent',
            field=models.IntegerField(verbose_name='肺活量优秀标准(ml)'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_name',
            field=models.CharField(max_length=50, verbose_name='班级'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='家长账号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户账号'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='description',
            field=models.TextField(verbose_name='测试说明'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='location',
            field=models.CharField(max_length=200, verbose_name='测试地点'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='test_date',
            field=models.DateTimeField(verbose_name='测试日期'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='title',
            field=models.CharField(max_length=100, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='bmi',
            field=models.FloatField(verbose_name='BMI指数'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='is_makeup',
            field=models.BooleanField(default=False, verbose_name='是否补测'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='run_50m',
            field=models.FloatField(verbose_name='50米跑(秒)'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='run_800m',
            field=models.IntegerField(verbose_name='800米跑(秒)'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='sit_and_reach',
            field=models.IntegerField(verbose_name='坐位体前屈(cm)'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='standing_jump',
            field=models.IntegerField(verbose_name='立定跳远(cm)'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.student', verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='测试时间'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.testplan', verbose_name='测试计划'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='total_score',
            field=models.IntegerField(verbose_name='总分'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='vital_capacity',
            field=models.IntegerField(verbose_name='肺活量(ml)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='手机号码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', '学生'), ('parent', '家长'), ('admin', '管理员')], max_length=10, verbose_name='用户类型'),
        ),
    ]
