# Generated by Django 5.1.7 on 2025-03-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_newscategory_sportsnews_newsnotification_newscomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sportsnews',
            name='category',
        ),
        migrations.RemoveField(
            model_name='newscomment',
            name='news',
        ),
        migrations.RemoveField(
            model_name='newscomment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='newsnotification',
            name='news',
        ),
        migrations.DeleteModel(
            name='NewsCategory',
        ),
        migrations.DeleteModel(
            name='NewsComment',
        ),
        migrations.DeleteModel(
            name='NewsNotification',
        ),
        migrations.DeleteModel(
            name='SportsNews',
        ),
    ]
