# Generated by Django 5.1.7 on 2025-03-23 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0006_remove_sportsnews_category_remove_newscomment_news_and_more'),
    ]

    operations = [
        # 尝试添加source_name列
        migrations.RunSQL(
            sql="""
            SET @stmt = (SELECT IF(
               EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sports_news' AND COLUMN_NAME = 'source_name'),
               'SELECT 1',
               'ALTER TABLE sports_news ADD COLUMN source_name VARCHAR(100) NULL'
            ));
            PREPARE stmt FROM @stmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE sports_news DROP COLUMN source_name;",
            elidable=True  # 忽略错误
        ),
        
        # 添加source_url列
        migrations.RunSQL(
            sql="""
            SET @stmt = (SELECT IF(
               EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sports_news' AND COLUMN_NAME = 'source_url'),
               'SELECT 1',
               'ALTER TABLE sports_news ADD COLUMN source_url VARCHAR(255) NULL'
            ));
            PREPARE stmt FROM @stmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE sports_news DROP COLUMN source_url;",
            elidable=True
        ),
        
        # 添加pub_date列
        migrations.RunSQL(
            sql="""
            SET @stmt = (SELECT IF(
               EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'sports_news' AND COLUMN_NAME = 'pub_date'),
               'SELECT 1',
               'ALTER TABLE sports_news ADD COLUMN pub_date DATETIME NULL'
            ));
            PREPARE stmt FROM @stmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="ALTER TABLE sports_news DROP COLUMN pub_date;",
            elidable=True
        ),
        
        # 尝试确保news_comment表有news_id列和外键约束
        migrations.RunSQL(
            sql="""
            -- 检查并添加news_id列
            SET @stmt = (SELECT IF(
               EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'news_comment' AND COLUMN_NAME = 'news_id'),
               'SELECT 1',
               'ALTER TABLE news_comment ADD COLUMN news_id INTEGER NULL'
            ));
            PREPARE stmt FROM @stmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            
            -- 尝试添加外键约束
            SET @stmt = (SELECT IF(
               EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
               WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'news_comment' AND CONSTRAINT_NAME = 'fk_news_comment_news'),
               'SELECT 1',
               'ALTER TABLE news_comment ADD CONSTRAINT fk_news_comment_news FOREIGN KEY (news_id) REFERENCES sports_news(id)'
            ));
            PREPARE stmt FROM @stmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="",  # 不需要反向操作
            elidable=True  # 忽略错误
        ),
        
        # 添加student_id列
        migrations.RunSQL(
            sql="""
            SET @stmt = (SELECT IF(
               EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
               WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'news_comment' AND COLUMN_NAME = 'student_id'),
               'SELECT 1',
               'ALTER TABLE news_comment ADD COLUMN student_id BIGINT NULL'
            ));
            PREPARE stmt FROM @stmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            
            -- 尝试添加学生外键约束
            SET @stmt = (SELECT IF(
               EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
               WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'news_comment' AND CONSTRAINT_NAME = 'fk_news_comment_student'),
               'SELECT 1',
               'ALTER TABLE news_comment ADD CONSTRAINT fk_news_comment_student FOREIGN KEY (student_id) REFERENCES student(id)'
            ));
            PREPARE stmt FROM @stmt;
            EXECUTE stmt;
            DEALLOCATE PREPARE stmt;
            """,
            reverse_sql="",
            elidable=True
        ),
    ]
