# Generated by Django 5.1.7 on 2025-03-23 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0007_add_missing_news_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('source_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='来源URL')),
                ('source_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='来源名称')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('featured_image', models.URLField(blank=True, max_length=500, null=True, verbose_name='特色图片URL')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='published', max_length=20, verbose_name='状态')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览次数')),
                ('keywords', models.CharField(blank=True, help_text='用逗号分隔的关键词，用于搜索', max_length=500, null=True, verbose_name='关键词')),
                ('is_featured', models.BooleanField(default=False, verbose_name='是否置顶')),
            ],
            options={
                'verbose_name': '体育新闻',
                'verbose_name_plural': '体育新闻管理',
                'db_table': 'sports_news',
                'ordering': ['-is_featured', '-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_approved', models.BooleanField(default=False, verbose_name='是否已审核')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to='fitness.student', verbose_name='学生')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fitness.sportsnews', verbose_name='新闻')),
            ],
            options={
                'verbose_name': '新闻评论',
                'verbose_name_plural': '新闻评论管理',
                'db_table': 'news_comment',
                'ordering': ['-created_at'],
            },
        ),
    ]
