# Generated by Django 5.1.7 on 2025-04-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0008_sportsnews_newscomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='是否及格'),
        ),
    ]
