# Generated by Django 5.1.7 on 2025-04-08 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0009_testresult_is_passed'),
    ]

    operations = [
    ]
