# Generated by Django 5.1.7 on 2025-04-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0010_auto_20250408_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='is_passed',
        ),
    ]
