# Generated by Django 5.1.7 on 2025-04-08 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0011_remove_testresult_is_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='test_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness.testresult', verbose_name='测试结果'),
        ),
    ]
