# Generated by Django 5.1.7 on 2025-04-08 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0012_healthreport_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthreport',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='healthreport',
            name='test_result',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fitness.testresult', verbose_name='测试成绩'),
        ),
    ]
