# Generated by Django 5.1.7 on 2025-04-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0013_remove_healthreport_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='height',
            field=models.FloatField(default=0, verbose_name='身高(cm)'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='weight',
            field=models.FloatField(default=0, verbose_name='体重(kg)'),
        ),
    ]
